MALSync/MALSync

- src/pages/pageUrls.js
- test/headless/test.js
Recently, AnimeZone changed some urls. The site currently requires login to view content (episode mirror list).
> AnimeZone fix

- src/pages/Aniwatch/main.ts
Just needed to get rid of a single ! in nextEpUrl to correctly determine whether we are on the last episode. Closes #443.
> Fix check for last episode in Aniwatch nextEpUrl function

- src/pages/AnimeZone/main.ts
`j.html` as parameter accepts string, which does not work, because `iframe` variable is actually object.
> [FIX] AnimeZone iframe fix

- src/_provider/Search/searchClass.ts
- src/pages/Crunchyroll/main.ts
- src/pages/Crunchyroll/tests.json
- webpackConfig/webextension.assets.js
Uses video ids with the xml api. This way we can get language independent title and identifier and makes it possible to identify the correct season on the overview page.
https://api.malsync.moe/page/Crunchyroll/major%25202nd
https://api.malsync.moe/page/Crunchyroll/jujutsu%2520kaisen
> Crunchyroll Fix

- assets/_locales/pt_BR/messages.json
Changes
----------
- Translate [syncPage_flashm_sync_manga_volume](https://github.com/MALSync/MALSync/pull/986/commits/9695656d62f0bcd8a813b443b937175a645b97b8#diff-e38c4a8fb4df0889515914e47ccc57330ce003d49fdbf3b2d19492fdead30b38R240-R253).
- Change the wording of [Package_Description](https://github.com/MALSync/MALSync/pull/986/commits/9695656d62f0bcd8a813b443b937175a645b97b8#diff-e38c4a8fb4df0889515914e47ccc57330ce003d49fdbf3b2d19492fdead30b38R94-R97).
- Use a better translation for "episode offset": "deslocamento de episódio".
- Replace "Manga" with "Mangá". ("manga" is the pt-pt's spelling, not pt-br's)
> Improve pt-br translations

- src/pages/animepahe/main.ts
- src/pages/animepahe/style.less
Fixed UI on animepahe overview page so it's no longer partially hidden by the anime cover image on the Relations and Recommendations tabs. Moved to top for consistency between tabs.
| Before | After |
| --- | --- |
| ![summary before](https://user-images.githubusercontent.com/7268094/147994512-40dc77b8-841a-4a1a-b85d-5e633d2d56cb.png) | ![summary after](https://user-images.githubusercontent.com/7268094/147994510-537b849e-f3b3-4c2d-a60e-a3a9178a4564.png) |
| ![relations before](https://user-images.githubusercontent.com/7268094/147994509-286508e8-b83c-4588-9b2c-dd0b29127b3c.png) | ![relations after](https://user-images.githubusercontent.com/7268094/147994513-7a4ff21d-f237-434f-b992-f3c78a6e4426.png) |
> animepahe: Fix overview page UI overlap

- src/pages/syncPage.ts
I found a bug regarding the rich presence. 
I was testing the extension with Komga and found out that if the manga has "volume" or "volumes" tag, the rich presence will display "Chapter: 0 of X".
Checking for the volumes fixes the issue. I also called the "UI_Volume" directly.
> Fixed bug regarding manga volumes in discord rich presence

- src/pages/diffUrls.json
- src/pages/playerUrls.js
These domains are currently used for dood player on otakufr.co.
> Add missing video domains for dood player

- src/pages/nineAnime/meta.json
Updated meta file for 9anime because they changed the format of their search url
> Change url used for 9anime search

- src/pages/diffUrls.json
- src/pages/playerUrls.js
This is the "[custom domain](https://streamsb.com/n29-Custom-domain.html)" used on Voiranime for StreamSB.
> Add missing StreamSB domain

- src/pages/NekoSama/main.ts
- src/pages/NekoSama/tests.json
What this PR does:
- Update tests URLs for NekoSama (remove the now unused `www.` subdomain, anime are now spited in 2 categories: vostfr and vf )
- Fix this bug: when anime title includes a digit, on overview episode number was wrong (the digit from the title and the episode number were concatenated)
What I checked:
-  Even if tests failed on GitHub (timeout), locally all tests are completed successfully.
- I build the web-extension, installed it in a clean Firefox profile and checked manually as well.
> Fix episodes detection in overview URL on nekosama

- src/pages/Jellyfin/main.ts
Now also recognises an anime if the path name is written in lowercase.
And it looks in the tags to see if its tagged as an anime as the default metadata provider of Jellyfin likes to add the 'Animation' genre instead of 'Anime', but always adds 'Anime' to tags.
> Improve anime detection on Jellyfin

- src/pages/diffUrls.json
- src/pages/playerUrls.js
* Domain used by voiranime.com
* `npm run build:missingPermissions`
> Add missing video domain for voe player

- src/pages/diffUrls.json
- src/pages/playerUrls.js
* Domain used on voiranime.com
* Partially automated with [this script](https://gist.github.com/louisroyer/7002619daf1313f6ea62dfd1e4c50281)
> Add missing domain for voe player

- src/pages/Voiranime/meta.json
- src/pages/diffUrls.json
Since 2023-02-17, voiranime.com redirects to the subdomain v2.voiranime.com The use of "v2" let me think it is only temporary, but currently VoirAnime is no longer detected out-of-the-box.
This commit should close #1625.
> Use VoirAnime subdomain

- src/pages/NekoSama/main.ts
- src/pages/NekoSama/tests.json
* URL format has changed: tests were broken
* For episode that have been published recently (I don't know if this will be permanent), anime title is no longer in `h1`, but in `h2` along with the episode number, separated by a `<br/>` : episode number detection was broken by this change
Example of what is currently at `.details > div`:
```html
<div class="info">
<h2>
<a href="/anime/info/19080-tomo-chan-wa-onnanoko_vostfr">Tomo-chan Is a Girl!</a>
<br>
Episode 7
</h2>
</div>
```
> Update NekoSama episode detection

- src/_provider/Shikimori/helper.ts
- src/_provider/Shikimori/metaOverview.ts
- src/_provider/Shikimori/single.ts
- src/utils/slugs.ts
- webpackConfig/httpPermissions.json
From .one to .me domain as one has been temp(?) lost
Source: https://shikimori.me/forum/news/505429-novyy-domen-sayta-shikimori-me Important part from there is:
`В любом случае новый домен сайта теперь shikimori.me. Даже когда/если
я верну старый домен, то основным доменом сайта останется новый, чтобы
не устраивать еще один переезд.`
Which roughly translates as shikimori.me would the main domain even after restoring old ones.
> Update shikimori domain name

- src/pages/Voiranime/meta.json
- src/pages/diffUrls.json
Recently, voiranime changed their subdomain from v4.voiranime.com
This pull request adds its new one which is v5.voiranime.com
EDIT: Might need to change the version for the diffUrls.json file
> Add new Voiranime subdomain

- src/pages/Komga/main.ts
- src/pages/Komga/style.less
- src/utils/mangaProgress/ModeFactory.ts
- src/utils/mangaProgress/modes/callback.ts
- src/utils/mangaProgress/modes/url.ts
Added:
- a way to handle oneshots (#1971)
- detection for onsite mal, al and kt links
- readerConfig (only for webtoon reading mode, can't make it work on other ones)
Changed:
- use the series title from its metadata for searching on sync pages instead of the series name
- ignore incognito reading
> Updated Komga

- src/pages/nineAnime/meta.json
This URL was missed with the recent domain change and generally not noticeable unless the anime is yet to release or cannot be found.
> Change aniwave search url from 9anime to aniwave

- src/pages/hachi/main.ts
Some changes were made to the overview page, so the offset handler no longer works. I'll likely make a pr at some other time that is able to fetch all the chapters, but this is a quick fix for now.
> [hachi] Disable offset handler

- src/pages/AnimeGO/main.ts
There are few anime overviews that doesn't have English and Japanese title
Example: https://animego.org/anime/oshi-no-ko-2307 \(Obviously, [Oshi no Ko](https://anilist.co/anime/150672/Oshi-No-Ko/)\)
- On 0.49% overviews extension crashes (no alternative headlines at all or only English)
- 30.56%: Japanese (日本語) headline is chosen
- Uses Russian title if no title found
- Locating English title correctly
> [AnimeGO] fix getTitle

- src/pages/Toonily/main.ts
- src/pages/Toonily/meta.json
- src/pages/Toonily/tests.json
Hey I noticed that toonily.com is not supported, while considering adding support I noticed that, now dead, toonily.net was supported, so I went ahead and adjusted the implementation. toonily.com does not have manga, only webtoon/manhwa, so the change was mostly as simple as switching out manga for webtoon. The CSS and such is unchanged and when loading the extension from a folder it seems to work as expected.
If I should change something, please let me know :)
Kind regards
Alistair1231
> update toonily page to support webtoon and change domain

- src/pages/AnimesOnline/main.ts
- src/pages/AnimesOnline/meta.json
- src/pages/AnimesOnline/style.less
- src/pages/AnimesOnline/tests.json
- src/pages/pages.ts
> New Page AnimesOnline

- src/pages/Guya/main.ts
Fixes chapter progress detection on guya/cubari.moe when using RTL (right-to-left reading mode). The reader reverses the order of the page elements, so `countAbove` on the `.ReaderImageWrapper` selector reports the wrong page number. The selector worked correctly when reading vertically and left-to-right.
> Fix: Guya/Cubari chapter progress detection

- src/pages/Miruro/main.ts
- src/pages/Miruro/tests.json
Hi,
Episode detection had stopped working in Malsync after Miruro.tv made changes to their URL for video players.
eg. 
from: https://www.miruro.tv/watch/101280/tensei-shitara-slime-datta-ken/20 
to: https://www.miruro.tv/watch/101280/20
the episode numbers are taken from url itself, so that logic had to be changed.
Best Regards,
Debjoy
> Fix episode detection not working after Miruro player page url changes

- webpackConfig/webextension.assets.js
Fixes #2486 
Sets `content_security_policy` to ensure all browsers use the same policy. Removes `upgrade-insecure-requests` from Firefox to allow making requests over HTTP.
> Override content security policy in manifest

- src/pages/Miruro/style.less
Hi,
Very small change, literally two word one line. 
Css adjustment done for malsync ui on the Info Page for Miruro website.
Before: 
After:
Best Regards,
Debjoy
> Fix malsync ui styling issue on info page [Miruro]

- webpackConfig/webextension.assets.js
Since Firefox 128 optional permissions are taken into account
> Use optional permissions in firefox

- src/_minimal/components/settings/settings-streaming.vue
closes #2595  
Quick PR with a simple quicklinks filter by type Anime/Manga. 
Found out it would be a nice QoL addition since number on links are increasing
Works basically like this:
> Quicklinks filter

- assets/_locales/pt_BR/messages.json
- assets/_locales/zh_CN/messages.json
- test/src/assets/_locales/locales.test.ts
Quick fix for "Incorrected locale information provided" error while using pt-BR + zh-CN locales in browser/extension
* pt_BR -> pt-BR
* zh_CN -> zh-CN
Also made tests in case of adding new locale in the future.
Until this is released there're these "fixes" for anyone using Brazilian Portuguese or Chinese:
* Revert to older version of extension from https://github.com/MALSync/MALSync/releases/tag/0.10.4
* Change browser language to OTHER than Brazilian Portuguese or Chinese
* Use "Force English" setting in Settings/Miscellaneous
> Fixed incorrected locale codes (pt-BR, zh-CN) + tests

- src/pages/KickAssAnime/main.ts
- src/pages/KickAssAnime/meta.json
The old ones got flagged by Cloudflare, so `https://kaa.mx` is created.
closes #2821
> Add new KickAssAnime domain

- assets/_locales/en/messages.json
- src/_minimal/components/settings/settings-structure-tracking.ts
- src/api/settings.ts
- src/utils/mangaProgress/MangaProgress.ts
solves #2811 
new setting changes the amount of a manga chapter that needs to be read before it is marked as read.
> add manga chapter completion percentage setting

- src/pages/AnimeKAI/style.less
AnimeKAI updated their stylesheet, which broke active episode highlighting.
> AnimeKAI fix active episode highlight

- src/_minimal/components/settings/settings-list-sync.vue
Some additions to list sync menu. List of changes:
1. Deauth buttons next to "Mirror"s - to remove existing connection to mirror if you do not want to sync it anymore
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
2. Display missing list as grid to save space
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
4. Group missing list by title name to avoid duplicates and save space
5. Highlight links - because I'm sure almost no one knows they can be clicked as they blends with whole button
Feel free to suggest changes since I'm not UI/UX guy
> ListSync - Group missings + deauth buttons

- src/utils/permissions.ts
For some browsers like Orion, `chrome.permissions.contains` sometimes return false when `origins` is an empty array.
> fix permissions

- src/pages-chibi/implementations/animeav1/main.ts
- src/pages-chibi/implementations/animeav1/style.less
- src/pages-chibi/implementations/animeav1/tests.json
- src/pages-chibi/pages.ts
- src/pages/playerUrls.js
This PR implement support for the Animeav1 site, as requested in the issue https://github.com/MALSync/MALSync/issues/3009.
Enables full site support with UI selector for both light and dark themes, and tests for both overview and sync pages.
Note: The last PR #3036 closed automatically due to a forced push in my fork, sorry!
> Add Animeav1 support [ES]

- src/utils/quicklinksBuilder.ts
Resolve the duplication of quicklinks with the same name by prioritizing chibi quicklinks over page quicklinks.
> Fixes same name item in quicklinks issue
