MALSync/MALSync

.gitignore
src/pages/animepahe/main.ts
src/pages/animepahe/style.less
src/pages/pageUrls.js
src/pages/pages.ts
src/pages/playerUrls.js

Add animepahe.com

---

README.md
package.json
src/pages/Animeflv/main.ts
src/pages/Jkanime/main.ts

- [Fix] Animeflv handleListHook
- [Fix] Jkanime handleListHook
- [Add] Windows compatibility scripts
- [Update] README.md

Some changes

---

assets/_locales/en/messages.json
assets/_locales/sv/messages.json

Not the best at managing GitHub PRs, pushing both instead of trying to figure out seperate

Added support for Swedish and changed some English strings

---

assets/_locales/en/messages.json

Changed "new url 'URL' set." to "New URL 'URL' set."

Fixed "new url" string for Database Correction

---

assets/_locales/id/messages.json

Some translation is kind of similar to another line (like on line 411 with 403, because Indonesia is kinda having a lack in word richness(?)). Also, I'm quite not sure about some line because I'm using English on any device as the main language. I will fix the translation if I made a mistake(s).

Indonesian Translation

---

src/pages/Wakanim/main.ts
src/pages/Wakanim/style.less
src/pages/pageUrls.js
src/pages/pages.ts
src/pages/playerUrls.js

Requested here : https://github.com/lolamtisch/MALSync/issues/16dee

Add Wakanim

---

assets/_locales/id/messages.json
assets/_locales/ms/messages.json

Including:
- Indonesia: Missing punctuation, and typo
- Malay: Create using Indonesian Dialect
- Fork: 2 times update.

Update Fork, Fix Indonesian, and Create Malay Translation

---

assets/_locales/fr/messages.json

Maybe he can rest some spelling error but I tried to make the more clean translation possible ^^

Add French Translation

---

src/pages/NekoSama/main.ts
src/pages/NekoSama/style.less
src/pages/pageUrls.js
src/pages/pages.ts
test/headless/test.js

Requested here : https://github.com/lolamtisch/MALSync/issues/163

Add NekoSama

---

src/pages/AnimeFever/main.ts
src/pages/AnimeFever/style.less
src/pages/pageUrls.js
src/pages/pages.ts
test/headless/test.js

i could not check if the player works since it does not load for me
everything else seems to work

add AnimeFever.tv

---

assets/_locales/ms/messages.json

I forgot to update it lol '-')

Update Malay Translation

---

src/pages/Goyabu/main.ts
src/pages/Goyabu/style.less
src/pages/pageUrls.js
src/pages/pages.ts

add goyabu.com

---

assets/_locales/tr/messages.json

Update-desu ~

---

src/pages/playerUrls.js

-Add player streamium
Example: [https://animeflv.net/ver/53172/vinland-saga-17](https://animeflv.net/ver/53172/vinland-saga-17)

Add player streamium

---

src/pages/playerUrls.js

add different vidstreaming url

---

src/pages/Aniwatch/main.ts
src/pages/Aniwatch/style.less
src/pages/pageUrls.js
src/pages/pages.ts

add aniwatch

---

src/_provider/AniList/list.ts
src/_provider/Kitsu/list.ts
src/_provider/Local/helper.ts
src/_provider/Local/import.ts
src/_provider/Local/list.ts
src/_provider/MyAnimeList/list.ts
src/_provider/Simkl/list.ts
src/_provider/listAbstract.ts
src/_provider/listFactory.ts
src/anilist/anilistClass.ts
src/background/backgroundIframe.ts
src/kitsu/kitsuClass.ts
src/minimal/minimalApp.vue
src/minimal/minimalApp/bookmarks.vue
src/minimal/minimalApp/bookmarksItem.vue
src/minimal/minimalApp/cleanTags/cleanTags.vue
src/minimal/minimalApp/components/settingsLogin.vue
src/minimal/minimalApp/listSync/listSync.vue
src/minimal/minimalApp/listSync/syncHandler.ts
src/minimal/minimalApp/settings.vue
src/minimal/minimalApp/updateCheck.vue
src/minimal/minimalStyle.less
src/myanimelist/myanimelistClass.ts
src/simkl/simklClass.ts
src/utils/Cache.ts
src/utils/epPrediction.ts
test/src/minimal/listSync/syncHandling.test.ts

List implementation

---

src/pages/Hidive/main.ts
src/pages/Hidive/style.less
src/pages/pageUrls.js
src/pages/pages.ts

Added support for the website hidive.com

Added support for Hidive

---

src/pages/MangaKatana/main.ts
src/pages/MangaKatana/style.less
src/pages/pageUrls.js
src/pages/pages.ts
test/headless/test.js

add mangakatana

---

src/pages/manga4life/main.ts
src/pages/manga4life/style.less
src/pages/pageUrls.js
src/pages/pages.ts
test/headless/test.js

add manga4life

---

src/pages/mangalivre/main.ts
src/pages/pageUrls.js

fix mangalivre and add nextep

---

src/_provider/singleAbstract.ts

This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/lolamtisch/malsync).

Apply fixes from CodeFactor

---

src/pages/AnimesHouse/main.ts
src/pages/AnimesHouse/style.less
src/pages/pageUrls.js
src/pages/pages.ts

add animeshouse

---

src/pages/AnimeFire/main.ts
src/pages/AnimeFire/style.less
src/pages/MonosChinos/main.ts
src/pages/MonosChinos/style.less
src/pages/pageUrls.js
src/pages/pages.ts
test/headless/test.js

add monoschinos & animefire

---

src/pages/NekoSama/main.ts

- Fix next page detection on firefox
- Add list

Fix NekoSama

---

src/pages/manga4life/main.ts

https://manga4life.com/read-online/Mashle-chapter-22.html

fix manga4life

---

assets/_locales/pt_BR/messages.json

Add some missing translations
The 're' prefix doesn't use hyphen

Update pt_BR translation

---

src/pages/Okanime/main.ts
src/pages/Okanime/style.less
src/pages/Okanime/tests.json
src/pages/pageUrls.js
src/pages/pages.ts
src/pages/playerUrls.js

Okanime is an arabic anime website.

Add Okanime

---

src/pages/MangaSee/main.ts
src/pages/manga4life/main.ts

Fixed issue with MangaSee/Manga4Life not detecting chapter change when changing chapter in reader

Fix MangaSee/Manga4Life Chapter Change

---

src/background/releaseProgress.ts

There is an Error when selecting needed Data for getPRogress.

Fixed wrong selection for get Progress

---

assets/_locales/ru/messages.json

Comrades are happy about it. Updated version!

MAL–Sync Russian Translation (ver.0.2)

---

assets/_locales/ru/messages.json

MAL-Sync (Russian Translation)

---

assets/_locales/pl/messages.json
src/_provider/singleAbstract.ts
src/pages/AnimeOdcinki/style.less
src/pages/AnimeZone/style.less
src/pages/FrixySubs/main.ts
src/pages/FrixySubs/meta.json
src/pages/FrixySubs/style.less
src/pages/FrixySubs/tests.json
src/pages/Shinden/main.ts
src/pages/Shinden/style.less
src/pages/Shinden/tests.json
src/pages/list.json
src/pages/pages.ts
src/pages/playerUrls.js

* Updated and fixed Polish translation 
* Added CDA player
* Updated Shinden overviewurl, added eplist and nextep
* Added FrixySubs page
* 'Fixed' singleAbstract.ts
* Updated AnimeZone, AnimeOdcinki, Shinden CSS

Update polish translation and pages

---

src/pages/OtakuFR/main.ts
src/pages/OtakuFR/meta.json
src/pages/OtakuFR/style.less
src/pages/OtakuFR/tests.json

Fix Otakufr

---

src/pages/Funimation/main.ts
src/pages/Funimation/meta.json
src/pages/Funimation/style.less

#533 
Multi Examples:
Log horizon
Highschool dxd
Assassination classroom
Noragami

add funimation multi season

---

src/pages/Goyabu/main.ts
src/pages/Goyabu/style.less

fix goyabu

---

src/pages/Netflix/main.ts

fix netflix

---

src/pages/Turkanime/main.ts

Highlighter feature matches with episodes that has the similar number and this PR fixes that issue.
PR has some refactoring for existing code

Fixes episode number mismatch

---

assets/_locales/de/messages.json

There is nothing more to say I guess. :)

Update German translation

---

assets/_locales/en/messages.json
src/_provider/Search/components/rules.vue
src/_provider/Search/correctionApp.vue
src/_provider/Search/correctionStyle.less
src/_provider/Search/rulesClass.ts
src/_provider/Search/searchClass.ts
src/_provider/singleFactory.ts
src/pages/pageInterface.ts
src/pages/syncPage.ts
src/utils/general.ts
src/utils/progress.ts
test/src/provider/rulesClass.test.ts
test/src/utils/apiStub.ts

https://github.com/erengy/anime-relations

[FEATURE] Use taiga anime-relations

---

src/pages/LynxScans/main.ts
src/pages/LynxScans/meta.json
src/pages/SecretScans/meta.json
src/pages/pages.ts

SecretScans has rebranded to LynxScans

Change SecretScans to LynxScans

---

assets/_locales/es/messages.json

Translation for the new strings introduced in v0.8.7

Update spanish translation

---

assets/_locales/pl/messages.json
src/pages/FrixySubs/main.ts
src/pages/FrixySubs/meta.json
src/pages/FrixySubs/style.less
src/pages/FrixySubs/tests.json
src/pages/Shinden/main.ts
src/pages/Shinden/meta.json

- Updated polish translation to v0.8.7
- Updated FrixySubs and Shinden pages

Polish pages, translation update

---

src/pages/ComicK/main.ts
src/pages/ComicK/meta.json
src/pages/ComicK/tests.json
src/pages/pages.ts

add comick

---

src/pages/Japanread/main.ts
src/pages/Japanread/meta.json
src/pages/Japanread/style.less
src/pages/Japanread/tests.json
src/pages/KangaryuTeam/main.ts
src/pages/KangaryuTeam/meta.json
src/pages/KangaryuTeam/style.less
src/pages/KangaryuTeam/tests.json
src/pages/list.json
src/pages/pages.ts

Added Kangaryu website and Japanread
Kangaryu is the website of a French translation team
Japanread is a more global manga website
Both are in French

Add Kangaryu & Japanread

---

src/pages/KangaryuTeam/main.ts
src/pages/KangaryuTeam/style.less

They updated their design recently so the container isn't matching with the whole website.
Fixed in this PR.

Update Kangaryu style

---

src/pages/Crunchyroll/beta.ts
src/pages/Crunchyroll/main.ts
src/pages/Crunchyroll/styleBeta.less
src/pages/syncPage.ts
src/utils/scriptProxy.ts
webpackConfig/webextension.assets.js

Crunchyroll beta

---

src/pages/Scantrad/main.ts
src/pages/Scantrad/style.less
src/pages/Scantrad/tests.json

The website has been recently updated (and the design so it was looking for the wrong elements & classes).

[BUGFIX] Fix Scantrad

---

assets/_locales/en/messages.json
src/api/settings.ts
src/minimal/minimalApp/settings.vue
src/pages/syncPage.ts

add filler/recap check

---

src/pages/JapScan/main.ts
src/pages/JapScan/meta.json
src/pages/JapScan/style.less
src/pages/JapScan/tests.json
src/pages/Japanread/main.ts

- Fix elementUrl on JapanRead when the user is logged in
- Fix Japscan domain

Various french pages improvements/fixes

---

src/pages/playerUrls.js

Samples:
https://strcloud.link/e/mYMXZWx2QDuBLQ/
https://streamta.pe/e/9bGD6zXWJWha217/
https://strtape.tech/e/ZxPAlb76KoUqQel/

Additional streamtape domains

---

src/pages/Japanread/main.ts
src/pages/Japanread/tests.json

Added getVolume() and nextEpUrl() support

Japanread improvements

---

src/pages/Plex/main.ts

A fix for https://github.com/MALSync/MALSync/issues/784

fix Plex connection URI retrieval

---

src/floatbutton/userscriptPwa.ts
src/index-webextension/pwa.ts
src/index.ts
webpackConfig/utils/pageUrls.js
webpackConfig/webextension.assets.js
webpackConfig/webextension.content.config.js

Support https://malsync.moe/pwa/

[TASK] Add pwa

---

src/_provider/listAbstract.ts

Additional manga sortings

---

assets/_locales/es/messages.json

Updated ES translation

---

src/pages/TRanimeizle/main.ts
src/pages/TurkAnime/main.ts

Related report
https://discord.com/channels/358599430502481920/369422195128270848/888109698719572018

Fix TRAnimeIzle URL issue

---

assets/_locales/en/messages.json
src/api/settings.ts
src/minimal/minimalApp/settings.vue
src/pages/syncPage.ts

add option to show malsync instead of anime/manga in the title

---

src/pages/BetterAnime/main.ts
src/pages/BetterAnime/meta.json

I had to remove the `Dublado` from the anime title cause it was giving wrong results. Hope this isn't a problem :)

Add support for dubbed animes in BetterAnime

---

eslint/rules/no-xss-jquery.js

The spacing was off for some lines and it was causing a minor annoyance. 
I potentially recommend using something like prettier to make the entire project consistent.

Make spacing consistent

---

src/pages/MangaHub/main.ts

Fixes issue with MALSync reloading when new message ad changes title to new message and back on repeat

Fix MangaHub

---

src/pages/diffUrls.json
src/pages/playerUrls.js

This domain is currently used for voe player on voiranime.com.

Add missing video domain for voe player

---

src/pages/MuitoManga/main.ts
src/pages/MuitoManga/meta.json
src/pages/MuitoManga/style.less
src/pages/MuitoManga/tests.json
src/pages/pages.ts

Add MuitoMangá

---

src/pages/EdelgardeScans/main.ts
src/pages/EdelgardeScans/meta.json
src/pages/HatigarmScanz/main.ts
src/pages/HatigarmScanz/meta.json
src/pages/HunlightScans/main.ts
src/pages/KKJScans/main.ts
src/pages/KKJScans/meta.json
src/pages/KrakenScans/main.ts
src/pages/LynxScans/main.ts
src/pages/LynxScans/style.less
src/pages/LynxScans/tests.json
src/pages/MethodScans/main.ts
src/pages/MethodScans/meta.json
src/pages/NonamesScans/main.ts
src/pages/NonamesScans/meta.json
src/pages/ZeroScans/main.ts
src/pages/ZeroScans/meta.json
src/pages/ZeroScans/style.less
src/pages/ZeroScans/tests.json
src/pages/pages.ts

This PR updates Zero Scans to work with new website design, makes Lynx Scans master copy for Genkan sites and removes all old/dead Genkan sites

Update Zero Scans and Genkan Sites

---

assets/_locales/fr/messages.json

* Add missing messages
* Fix typos

Updated FR translation

---

package-lock.json
package.json

Revert "Update Node.js to >=v16.15.1"

---

src/pages/diffUrls.json
src/pages/playerUrls.js

Add missing video domain for streamsb

---

src/_provider/Search/correctionApp.vue
src/api/settings.ts
src/floatbutton/init.ts
src/floatbutton/userscript.ts
src/pages/Okanime/style.less
src/pages/syncPage.ts

- The floating button opens the correction ui by default
- Adds an edit icon
- Hide button if not needed

[TASK] Add edit floating button

---

src/pages/diffUrls.json
src/pages/playerUrls.js

Used on voiranime.
example: https://voiranime.com/anime/fumetsu-no-anata-e-2/fumetsu-no-anata-e-s2-05-vostfr/

Add missing StreamSB domain

---

src/pages/diffUrls.json
src/pages/playerUrls.js

Used on voiranime.com
Example:
https://20demidistance9elongations.com/e/pghs4j05zuw5 on https://voiranime.com/anime/boku-no-hero-academia-6/boku-no-hero-academia-6-10-vostfr/

Add missing domain for VOE player

---

src/pages/diffUrls.json
src/pages/playerUrls.js

Used on voiranime.com
Example:
https://toxitabellaeatrebates306.com/e/9avy4wzf37x5 on https://voiranime.com/anime/bocchi-the-rock/bocchi-the-rock-11-vostfr/

Add missing domain for VOE player 

---

assets/_locales/en/messages.json
src/_minimal/components/settings/settings-streaming.vue
src/_minimal/components/settings/settings-structure-etc.ts
src/_minimal/components/settings/settings-structure-tracking.ts
src/_minimal/minimalClass.ts
src/_minimal/router.ts
src/_minimal/views/bookmarks.vue
src/_provider/Shikimori/helper.ts
src/_provider/Shikimori/list.ts
src/_provider/Shikimori/metaOverview.ts
src/_provider/Shikimori/oauth.ts
src/_provider/Shikimori/search.ts
src/_provider/Shikimori/single.ts
src/_provider/listFactory.ts
src/_provider/metaDataFactory.ts
src/_provider/searchFactory.ts
src/_provider/singleFactory.ts
src/api/settings.ts
src/index-webextension/shikiOauth.ts
src/index.ts
src/installPage/main.vue
src/popup.ts
src/utils/general.ts
src/utils/slugs.ts
webpackConfig/httpPermissions.json
webpackConfig/utils/pageUrls.js
webpackConfig/webextension.assets.js
webpackConfig/webextension.content.config.js

Add Shikimori provider

---

src/pages/diffUrls.json
src/pages/playerUrls.js

Example: https://neko-sama.fr/anime/episode/19050-4-nin-wa-sorezore-uso-wo-tsuku-11-vostfr

Add new player domain for Neko-Sama

---

src/_provider/MyAnimeList_api/single.ts
src/_provider/singleAbstract.ts

https://github.com/MALSync/MALSync/issues/1528

fixed issue: Rewatch count not increased

---

src/pages/diffUrls.json
src/pages/playerUrls.js

 Add missing video domain for voe player 

---

src/pages/diffUrls.json
src/pages/playerUrls.js

Example: https://fusevideo.net/e/1XYb73qBBJVekmG on https://neko-sama.fr/anime/episode/19002-koori-zokusei-danshi-to-cool-na-douryou-joshi-03-vostfr

Add new domain for NekoSama videos

---

src/pages/Isekaiscan/main.ts
src/pages/Isekaiscan/meta.json
src/pages/Isekaiscan/style.less
src/pages/Isekaiscan/tests.json
src/pages/pages.ts

Added Isekaiscan domain.
Straight copy from #757 and #857.

added isekaiscan pages

---

src/_minimal/views/overview.vue
src/_provider/AniList/single.ts
src/_provider/Kitsu/single.ts
src/_provider/Search/rulesClass.ts
src/_provider/Search/searchClass.ts
src/_provider/Simkl/single.ts
src/_provider/helper.ts
src/_provider/singleAbstract.ts
src/_provider/singleFactory.ts

Use provider IDs for episode mapping rules

---

src/pages/diffUrls.json
src/pages/playerUrls.js

* Used on voiranime.com
* `npm run build:missingPermissions` (turkanime line not staged)

Add missing streamsb player

---

src/pages/TurkAnime/main.ts

https://discord.com/channels/358599430502481920/369422195128270848/1074401727517822996

fix(turkanime): improve episode number matching expression

---

src/pages/diffUrls.json
src/pages/playerUrls.js

Used on voiranime.com
Example: https://v2.voiranime.com/anime/benriya-saitou-san-isekai-ni-iku/benriya-saitou-san-isekai-ni-iku-11-vostfr/ (player SB)

Add missing player for voiranime

---

src/pages/diffUrls.json
src/pages/playerUrls.js

Example use:
https://v2.voiranime.com/anime/reborn-to-master-the-blade/reborn-to-master-the-blade-11-vostfr/ (player "myTV")

Add new player URL for vidmoly

---

src/pages/playerUrls.js
webpackConfig/autoUrls.mjs

Since it use redirection, this will avoid further work. (I should have done it directly in the first PR, sorry about that)

AutoUrl for vidmoly

---

src/pages/Kaguya/main.ts
src/pages/Kaguya/meta.json
src/pages/Kaguya/tests.json

The website's domain was changed to kaguya.app.

[Kaguya] Update domain

---

src/pages/Voiranime/meta.json
src/pages/diffUrls.json

Update Voiranime main domain

---

src/pages/NeoxScans/main.ts
src/pages/NeoxScans/meta.json
src/pages/NeoxScans/style.less
src/pages/NeoxScans/tests.json
src/pages/pages.ts

As neox and 1stkissmanga use the same wordpress theme, I copied the implementation for 1stkissmanga and made some tweaks
closes #1939

Add NeoxScans support

---

src/pages/FMTeam/main.ts
src/pages/FMTeam/style.less
src/pages/FMTeam/tests.json

There is a timeout in the test with Github Actions but they are working fine in local

refactor(FMTeam): update page

---

src/pages/NekoSama/main.ts
src/pages/NekoSama/meta.json
src/pages/NekoSama/tests.json
src/pages/diffUrls.json

This domain change seems permanent (HTTP 301: Moved Permanently).

Update domain name for NekoSama

---

src/pages/HinataSoul/main.ts
src/pages/HinataSoul/meta.json
src/pages/HinataSoul/style.less
src/pages/HinataSoul/tests.json
src/pages/pages.ts

I couldn't run the tests, since it was taking way too long and it looked like it was frozen. But everything should work.
`paginationNext` wasn't running because `elementEp` was broken, but that should be fixed.
I'm testing for episode 37, but I'm not sure if pagination works in testing, will remove if it doesn't.

Add HinataSoul

---

src/pages/diffUrls.json
src/pages/playerUrls.js

See [this video](https://animecat.net/anime/episode/19693-jidou-hanbaiki-ni-umarekawatta-ore-wa-meikyuu-wo-samayou-08_vostfr) for an example of use.

Add missing domain for fusevideo

---

src/pages/manga4life/main.ts

As per title I've added manga progression for Manga4Life, it uses the same config as MangaSee

Added manga progression tracking to Manga4Life

---

src/pages/tmofans/meta.json

Added two more URLs to the TMO meta.json

Added more URLs to the TMO meta.json

---

src/pages/tmofans/meta.json

Added more URLs to TMO meta.json

---

src/pages/Shinden/meta.json
src/pages/YugenAnime/meta.json

Fix Quicksearch Link for YugenAnime and Shindel

---

src/pages/YugenAnime/meta.json

I would like to sincerely apologize for my mistake of not fully testing all the changes made in the code before sending the last pull request. This commit fixes the problem caused by the last one.

Fix URL Match and Quicksearch of YugenAnime

---

src/pages/ComicK/main.ts
src/pages/ComicK/meta.json
src/pages/diffUrls.json

Please point out if there is mistakes

New comick domain

---

src/pages/ManhuaUS/main.ts
src/pages/ManhuaUS/meta.json
src/pages/ManhuaUS/style.less
src/pages/ManhuaUS/tests.json
src/pages/pages.ts

adding Manhuaus

---

src/pages/Tachidesk/main.ts
src/pages/Tachidesk/meta.json
src/pages/Tachidesk/style.less
src/pages/pages.ts

solves #1014 
much thanks to @Pikcee

Add Tachidesk

---

src/api/settings.ts

Current output:
`Update settings/anilistOptions option to [object Object]`
Steps to recreate:
1. goto anilist 
2. click on anime list

Fixing faulty console output

---

src/pages/AnimeBuff/main.ts
src/pages/AnimeBuff/meta.json
src/pages/AnimeBuff/style.less
src/pages/AnimeBuff/tests.json
src/pages/pages.ts

- Geo-restricted
- Some titles are hidden by 404, so code handles it

Add AnimeBuff [RU] (fix #2347)

---

src/pages/playerUrls.js

Found on https://v5.voiranime.com/ using Moon player
`*://designparty.sx/e/*`

Add Voiranime's Filemoon player custom domain

---

src/pages/NekoSama/main.ts
src/pages/NekoSama/tests.json

This website updated the way they display episode list.

Fix detection of episodes list for Neko-Sama

---

src/pages/MangaRead/main.ts
src/pages/MangaRead/meta.json
src/pages/MangaRead/style.less
src/pages/MangaRead/tests.json
src/pages/list.json
src/pages/pages.ts

Add the MangaRead website
Note the search is not 100% compatible.
It normally uses the `{searchtermPlus}` but some characters, like quotes, are encoded as `{searchterm}`.

Add mangaread website

---

src/pages/Anime365/main.ts
src/pages/Anime365/meta.json
src/pages/Anime365/tests.json
src/pages/playerUrls.js

`smotret-anime.com` already redirects to `smotret-anime.net`

Change Anime365 domain

---

src/pages/Miruro/main.ts
src/pages/Miruro/style.less

Hi, due to recent changes in the site Miruro, malsync had stopped working in overview page. 
I did few modification to change mostly the selectors and some conditions to make it work again.
There is a minor css fix as well for the malsync ui.
Best,
Debjoy

Fix malsync not working for Miruro in overview page

---

src/pages/TempleScan/main.ts
src/pages/TempleScan/meta.json
src/pages/TempleScan/style.less
src/pages/TempleScan/tests.json
src/pages/pages.ts

Added support for Temple Scan: https://templescan.net/
Only works on recent chapters as the url structure changes as shown below
https://templescan.net/comic/my-introverted-boy/70520-chapter-39
https://templescan.net/comic/my-introverted-boy/chapter-40

TempleScan Support

---

src/pages/ReaperScans/main.ts

fixes #2607
Did it since I had time

ReaperScans isOverviewPage fix

---

src/pages/Bakashi/main.ts
src/pages/Bakashi/tests.json

Bakashi movies tracking

---

src/pages/Kavita/main.ts
src/pages/Kavita/meta.json
src/pages/Kavita/style.less
src/pages/Kavita/tests.json
src/pages/pages.ts

Add Kavita Page

---

webpackConfig/autoUrls.mjs

Redirect is now done in javascript.

Update autoUrls's voe function

---

src/pages/Bakashi/main.ts
src/pages/Bakashi/meta.json
src/pages/Bakashi/tests.json

I have properly tested the new domain, and it all seems to be working fine.

New Bakashi domain

---

src/pages/Anime365/main.ts
src/pages/Anime365/meta.json
src/pages/Anime365/tests.json
src/pages/playerUrls.js

- `smotret-anime.net` redirects to `smotret-anime.org`
- Add mirrors

[Anime365] update domains

---

src/pages/Aniworld/style.less

I added better styling for the Website Aniworld. I have been using this styling my self via Tampermonkey and thought i share it with others.

better styling for Aniworld

---

src/pages/AnimeKAI/main.ts
src/pages/AnimeKAI/meta.json
src/pages/AnimeKAI/style.less
src/pages/AnimeKAI/tests.json
src/pages/pages.ts
src/pages/playerUrls.js
test/headless/test.js

add AnimeKAI support

---

src/pages/AnimeLib/main.ts

Just a small fix, since I noticed a page is directs you to `/watch` endpoint but all required params are still not loaded (`?episode=1234` etc.)
Also either I messed up selecting current episode button with jQ or there were changes in website - anyway also fixed.

AnimeLib - Fix getting current episode 

---

src/pages/playerUrls.js

This pull request adds support for a new player server used by AnimeWorld.

Added animeworld playerURL

---

src/pages/AnimeKAI/main.ts

Fixes the problem where navigating to AnimeKAI via "Continue watching" causes the wrong episode to be detected

Animekai fix tracking issue

---

src/pages/AniDream/main.ts
src/pages/AniDream/meta.json
src/pages/AniDream/style.less
src/pages/AniDream/tests.json
src/pages/pages.ts

I have added the website anidream.cc

Added AniDream Integration

---

src/pages-chibi/implementations/animeav1/main.ts
src/pages-chibi/implementations/animeav1/style.less

Updates Animeav1 with suggestions from #3009:
* Moved overview UI Injection to more convinient placement.
* Updated overview last viewed episode style to match website rounded borders.

Update Animeav1 uiInjection and style

---

src/pages-chibi/implementations/StoneScape/main.ts
src/pages-chibi/implementations/StoneScape/style.less
src/pages-chibi/implementations/StoneScape/tests.json
src/pages-chibi/pages.ts

Add support to https://stonescape.xyz

Add support to StoneScape

---

src/pages-chibi/implementations/Comikey/main.ts
src/pages-chibi/implementations/Comikey/style.less

i hope this is last commit for comikey

fix title detection for Comikey

---

src/pages-chibi/implementations/Atsumaru/main.ts
src/pages-chibi/implementations/Atsumaru/style.less
src/pages-chibi/implementations/Atsumaru/tests.json
src/pages-chibi/pages.ts

add support to atsu.moe

---

src/pages-chibi/implementations/ComicTop/main.ts
src/pages-chibi/implementations/ComicTop/style.less
src/pages-chibi/implementations/ComicTop/tests.json
src/pages-chibi/pages.ts

add support to ComicTop
